services:
  # A Docker web service
  - type: web
    name: pb-gitlab-integration
    env: node
    branch: main # optional (defaults to master)
    buildCommand: npm install
    startCommand: node app.js    numInstances: 3 # optional (defaults to 1)
    envVars:
      - key: PRODUCTBOARD_INTEGRATION_ID
        value: <enter-integration-id-here>
      - key: GITLAB_TOKEN
        value: <enter-gitlab-token-here>
      - key: GITLAB_PROJECT_ID
        value: <enter-gitlab-project-id-here>
      - key: PRODUCTBOARD_TOKEN
        value: <enter-productboard-token-here>
