services:
  - type: web
    name: productboard-gitlab-integration
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node app.js    
    envVars:
      - key: PRODUCTBOARD_INTEGRATION_ID
        value: <enter-integration-id-here>
      - key: GITLAB_TOKEN
        value: <enter-gitlab-token-here>
      - key: GITLAB_PROJECT_ID
        value: <enter-gitlab-project-id-here>
      - key: PRODUCTBOARD_TOKEN
        value: <enter-productboard-token-here>
